<?php
$z[0]=Array("arcurl","",99,114);
$z[1]=Array("title","",123,137);
$z[2]=Array("title","",155,169);
$z[3]=Array("arcurl","",227,242);
$z[4]=Array("title","",251,265);
$z[5]=Array("description","",443,493);
$z[5][4]['function']="cn_substr(@me,100)";
$z[6]=Array("arcurl","",522,537);
$z[7]=Array("pubdate","",620,667);
$z[7][4]['function']="MyDate('Y-m-d',@me)";
$z[8]=Array("click","",717,731);

?>