<?php
$z[0]=Array("arcurl","",98,113);
$z[1]=Array("title","",122,136);
$z[2]=Array("title","",154,168);
$z[3]=Array("arcurl","",224,239);
$z[4]=Array("title","",248,262);
$z[5]=Array("picname","",305,321);
$z[6]=Array("title","",328,342);
$z[7]=Array("description","",405,455);
$z[7][4]['function']="cn_substr(@me,100)";
$z[8]=Array("arcurl","",484,499);
$z[9]=Array("pubdate","",563,610);
$z[9][4]['function']="MyDate('Y-m-d',@me)";
$z[10]=Array("click","",660,674);

?>