<dl class="clearfix">
                  <dt><a href="[field:arcurl/]" target="_blank" title="[field:title/]">
                      <img src="[field:picname/]" alt="[field:title/]" title="[field:title/]"  width="180" height="108" /></a></dt>
                  <dd>
                      <h3>
                          <a href="[field:arcurl/]" title="¡°[field:title/]" target="_blank">[field:title/]</a></h3>
                      <p class="li_cont">[field:description function="cn_substr(@me,100)"/]...
                          <a href="http://seo.ujiuye.com/zhinan/2016/1183.html" target="_blank">ÏêÏ¸ ></a></p>
                      <ul class="li_side clearfix">
                          <li class="li_else"><span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span><span>ÔÄ¶Á£¨[field:click/]£©</span><span class="shouc">ÊÕ²Ø£¨0£©</span></li>
                     </ul>
                  </dd>
              </dl>