<?php
$z[0]=Array("arcurl","",54,69);
$z[1]=Array("title","",94,108);
$z[2]=Array("picname","",144,160);
$z[3]=Array("title","",167,181);
$z[4]=Array("title","",190,204);
$z[5]=Array("arcurl","",332,347);
$z[6]=Array("title","",358,372);
$z[7]=Array("title","",390,404);
$z[8]=Array("description","",456,506);
$z[8][4]['function']="cn_substr(@me,100)";
$z[9]=Array("pubdate","",728,775);
$z[9][4]['function']="MyDate('Y-m-d',@me)";
$z[10]=Array("click","",794,808);

?>