<?php
$z[0]=Array("arcurl","",68,83);
$z[1]=Array("title","",92,106);
$z[2]=Array("title","",124,138);
$z[3]=Array("arcurl","",194,209);
$z[4]=Array("title","",218,232);
$z[5]=Array("picname","",275,291);
$z[6]=Array("title","",298,312);
$z[7]=Array("description","",364,414);
$z[7][4]['function']="cn_substr(@me,100)";
$z[8]=Array("arcurl","",441,456);
$z[9]=Array("pubdate","",520,567);
$z[9][4]['function']="MyDate('Y-m-d',@me)";
$z[10]=Array("click","",617,631);

?>