<?php
$z[0]=Array("arcurl","",98,113);
$z[1]=Array("title","",124,138);
$z[2]=Array("title","",158,172);
$z[3]=Array("arcurl","",228,243);
$z[4]=Array("title","",254,268);
$z[5]=Array("picname","",311,327);
$z[6]=Array("title","",336,350);
$z[7]=Array("description","",413,463);
$z[7][4]['function']="cn_substr(@me,100)";
$z[8]=Array("arcurl","",492,507);
$z[9]=Array("pubdate","",571,618);
$z[9][4]['function']="MyDate('Y-m-d',@me)";
$z[10]=Array("click","",668,682);

?>