<?php
$z[0]=Array("arcurl","",99,114);
$z[1]=Array("title","",123,137);
$z[2]=Array("title","",155,169);
$z[3]=Array("arcurl","",227,242);
$z[4]=Array("title","",251,265);
$z[5]=Array("picname","",308,324);
$z[6]=Array("title","",331,345);
$z[7]=Array("description","",398,448);
$z[7][4]['function']="cn_substr(@me,100)";
$z[8]=Array("arcurl","",477,492);
$z[9]=Array("pubdate","",575,622);
$z[9][4]['function']="MyDate('Y-m-d',@me)";
$z[10]=Array("click","",672,686);

?>