<?php
$z[0]=Array("arcurl","",99,114);
$z[1]=Array("title","",123,137);
$z[2]=Array("title","",155,169);
$z[3]=Array("arcurl","",242,257);
$z[4]=Array("title","",266,280);
$z[5]=Array("picname","",327,343);
$z[6]=Array("title","",350,364);
$z[7]=Array("description","",417,467);
$z[7][4]['function']="cn_substr(@me,100)";
$z[8]=Array("arcurl","",494,509);
$z[9]=Array("pubdate","",592,639);
$z[9][4]['function']="MyDate('Y-m-d',@me)";
$z[10]=Array("click","",689,703);

?>