<?php
$z[0]=Array("global","",187,211);
$z[0][4]['name']="cfg_about";
$z[1]=Array("channelartlist","\r                <li>\r\r                    <dl>\r\r                        <dt>\r\r                            {dede:field name='typename'/}</dt>\r\r                        <dd>\r                            {dede:channel type='son' noself='yes' }\r                            <a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a>\r                            {/dede:channel}\r                        </dd>\r\r                    </dl>\r\r                </li>\r\r                ",315,860);
$z[1][4]['row']="3";
$z[1][4]['typeid']="33,34,35";
$z[2]=Array("flink","  [field:link /]  ",997,1075);
$z[2][4]['titlelen']="20";
$z[2][4]['row']="20";
$z[2][4]['type']="text";
$z[3]=Array("global","",1180,1206);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",1342,1374);
$z[4][4]['name']="cfg_templets_skin";

?>