<?php
$z[0]=Array("global","",168,193);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",255,280);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",338,363);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",394,420);
$z[3][4]['name']="cfg_dataurl";
$z[4]=Array("global","",546,573);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",642,669);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",672,698);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",853,880);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",892,924);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",971,997);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("mda","",1052,1081);
$z[10][4]['name']="468x60_SSP";
$z[11]=Array("global","",1354,1379);
$z[11][4]['name']="cfg_cmsurl";
$z[12]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",1417,1660);
$z[12][4]['type']="top";
$z[12][4]['row']="10";
$z[12][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[13]=Array("global","",1752,1777);
$z[13][4]['name']="cfg_cmsurl";
$z[14]=Array("tag","\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",2554,2684);
$z[14][4]['row']="10";
$z[14][4]['getall']="1";
$z[14][4]['sort']="month";
$z[15]=Array("mda","",2825,2854);
$z[15][4]['name']="950x90_SSP";

?>