<?php
$z[0]=Array("typelink","",162,179);
$z[1]=Array("arcurl","",241,256);
$z[2]=Array("title","",274,288);
$z[3]=Array("picname","",304,320);
$z[4]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a target='_blank' href='{@me['arcurl']}'><img src='{@me['litpic']}' height=123 width=200/></a>\"); ",412,587);
$z[4][4]['runphp']="yes";
$z[5]=Array("description","",644,664);
$z[6]=Array("arcurl","",679,694);
$z[7]=Array("click","",867,881);

?>