<?php
$z[0]=Array("typelink","",162,179);
$z[1]=Array("arcurl","",241,256);
$z[2]=Array("title","",274,288);
$z[3]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a target='_blank' href='{@me['arcurl']}'><img src='{@me['litpic']}' height=123 width=200/></a>\"); ",413,588);
$z[3][4]['runphp']="yes";
$z[4]=Array("description","",645,665);
$z[5]=Array("arcurl","",680,695);
$z[6]=Array("click","",868,882);

?>