<li>	<!--	一篇文章就是从这里开始	-->
					<div class="blogli1">
						<div class="blogli2">
							<div class="blogico"><a href="#" target="_blank">[field:typelink/]</a></div>
							<div class="blogbiaoti">
								<a href="[field:arcurl/]" target="_blank">[field:title/]</a>  <img src="../images/new.gif">
							</div>
						</div>
						<div class="blogli3">
							<div class="blogimg">
[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a target='_blank' href='{@me['arcurl']}'><img src='{@me['litpic']}' height=123 width=200/></a>"); [/field:array]
							</div>
							<div class="blogp1">
								<p>[field:description/]......<a href="[field:arcurl/]" target="blank" style="color:#1abc9c;">继续阅读 »</a></p>
							</div>
							<div class="blogp2">
								<span1 class="blogspan1">查看 <span class="blogspan2">[field:click/]</span> 次</span>
							</div>
						</div>
					</div>
				</li>	<!--	一篇文章就是从这里结束	-->