<ul>
						<li><a class="ta" href="[field:arcurl /]">[field:title/]</a></li>
						
						<p>
	     [field:id runphp='yes'] $aid = @me; $row = $GLOBALS['dsql']->GetOne("Select body From `dede_addonarticle` where aid='$aid' "); @me = cn_substr(strip_tags("{$row['body']}"),420);[/field:id]...</p><span style="float:right;margin-top:25px"><a style="color:#c60202;margin-top:20px" href="[field:arcurl /]">更多>></a></span>
						
                    </ul>