
<field:title itemname="留言标题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:title>

<field:content itemname="留言类容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>

<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:dlc itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dlc>
