<?php
$z[0]=Array("field","",11,37);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",49,77);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",86,115);
$z[2][4]['name']="typename";
$z[3]=Array("field","",117,146);
$z[3][4]['name']="typename";
$z[4]=Array("channel"," <a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a> ",189,318);
$z[4][4]['type']="son";
$z[4][4]['noself']="yes";

?>