<?php
$z[0]=Array("global","",136,168);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",370,402);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",516,548);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",907,939);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("channelartlist","\r\n                <li class=\"nav_li1\"><a href=\"{dede:field name='typeurl'/}\"  style=\"font-family:'微软雅黑'\">{dede:field name='typename'/}</a>\r\n                    <ul>\r\n                        {dede:channel type='son' noself='yes' }\r\n                        <li><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n                        {/dede:channel}\r\n                    </ul>\r\n                    ",1266,1742);
$z[4][4]['row']="7";
$z[4][4]['typeid']="top";

?>