<?php
$z[0]=Array("global","",677,709);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",775,807);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",880,912);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1024,1056);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1127,1159);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1219,1251);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("include","",1298,1333);
$z[6][4]['filename']="head.htm";
$z[7]=Array("global","",2016,2048);
$z[7][4]['name']="cfg_templets_skin";
$z[8]=Array("global","",3428,3460);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("field","\r    \$ID = @me;\r    \$sql = “SELECT * FROM `dede_arctype` WHERE id=\$ID”;\r    \$query = mysql_query(\$sql);\$row=mysql_fetch_array(\$query);\r    \$relID = “\$row[reid]“;\r    if(\$relID == 0) {@me = \$row[typename];}\r    else{\$sql = “SELECT `typename` FROM `dede_arctype` WHERE id=\$relID”;\r    \$query = mysql_query(\$sql);\r    \$row=mysql_fetch_array(\$query);\r    @me = \$row[typename];}\r    ",3549,3999);
$z[9][4]['name']="typename";
$z[9][4]['runphp']="’yes’";
$z[10]=Array("channel","\r\r<li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\r    ",4020,4121);
$z[11]=Array("global","",4202,4234);
$z[11][4]['name']="cfg_templets_skin";
$z[12]=Array("global","",4369,4401);
$z[12][4]['name']="cfg_templets_skin";
$z[13]=Array("global","",4484,4516);
$z[13][4]['name']="cfg_templets_skin";
$z[14]=Array("field","",4745,4774);
$z[14][4]['name']="typename";
$z[15]=Array("global","",6046,6078);
$z[15][4]['name']="cfg_templets_skin";

?>